
services:
  django-web:
    depends_on: 
      - django-postgresql
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-web
    ports:
     - "8080:8000"
    restart: always
    volumes: 
      - .:/app
    working_dir: /app/django_web

  django-postgresql:
    container_name: djangodb
    image: postgres 
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/app/data
